### PR TITLE
solarnet: add storage hosts sirius and pollux

### PR DESCRIPTION
**Pull request by lgierth**
I take name suggestions, right now it's storage1.i.ipfs.io

### CODE REVIEW

**Comment by lgierth** [comment]
> whyrusleeping 5:36 PM @lgierth Sirius 

`sirius` it is.

**Comment by lgierth** [comment]
Eeh `pollux` it is. The other storage node is already named `sirius`.

**Comment by jbenet** [comment]
maybe add `sirius` here too?

**Comment by lgierth** [comment]
Added `sirius` and `pollux`

**Pull request merged**
