### PR TITLE
Make use of cjdns for Prometheus/API/Gateway authentication

### PR DESCRIPTION
**Pull request by lgierth**
- gateway at http://[fc12::3456]:8080
- api at http://[fc12::3456]:5001
- prometheus at http://[fc12::3456]:80 / http://metrics.ipfs.io

All of them require authentication with a whitelisted
cjdns IPv6 address (see secrets.yml).

The other three commits are semi-random fixes.

### CODE REVIEW

**Comment by jbenet** [comment]
I think this LGTM.

**Comment by jbenet** [comment]
`prometheus at http://[fc12::3456]:80` does it have to be 80 ? maybe we could keep 80 allocated (for nginx)? (would be nicer to reuse the same ports)

**Comment by lgierth** [comment]
That's simply a vhost, which only gets hit if the request's Host header is metrics.ipfs.io -- anything else will hit the gateway

**Comment by jbenet** [comment]
@lgierth ah ok sounds good :

**Pull request merged**
