### PR TITLE
Standardize README

### PR DESCRIPTION
**Pull request by RichardLitt**
See ipfs/community#124

### CODE REVIEW

**Comment by diasdavid** [comment]
LGTM :)

**Comment by diasdavid** [comment]
mind also updating the year on the LICENSE file?

**Comment by RichardLitt** [comment]
Not sure I can legally do that, actually.

**Comment by lgierth** [comment]
The name on the copyright should maybe be updated to something like "The IPFS Team" too

**Comment by RichardLitt** [comment]
@lgierth that takes more effort, apparently. I'm not sure how exactly, but @jbenet is looking into it.

**Pull request merged**
