### PR TITLE
gateway: offer https with self-signed cert

### PR DESCRIPTION
**Pull request by lgierth**
License: MIT
Signed-off-by: Lars Gierth <larsg@systemli.org>

### CODE REVIEW

**Comment by lgierth** [comment]
Forgot to mention, this currently runs on earth. Also, the certificate is for ipfs.io -- since I'm about to switch the gateway over to ipfs.io, and the certificate is invalid (self-signed) anyway, I figured I'd omit making one for gateway.ipfs.io altogether.

**Comment by jbenet** [comment]
> I figured I'd omit making one for gateway.ipfs.io altogether.

we'll still need one to make sure `https://gateway.ipfs.io/...` redirects safely to ipfs.  We'll have to get a wildcard cert anyway, for `dist.ipfs.io`

**Comment by lgierth** [comment]
Right, made it a wildcard cert

**Comment by jbenet** [comment]
Still havent heard from rapidssl. i'll email them.

**Pull request merged**
