### PR TITLE
More documentation

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
Initial version of some documentation. First pass.

Part of https://github.com/ipfs/infrastructure/issues/185 and making the documentation better.

Missing things, maybe this is something we can work together on. @lgierth please add/change anything you seem fit.

@hsanjuan @Kubuxu please mention things you think is missing from our documentation so we can add it.

### CODE REVIEW

**Comment by hsanjuan** [comment]
This looks good to me. It's a very good start. I'm missing a:

  * How to get access to the infra

And it would not hurt to have a guide to create, deploy, play with a dev cluster.

**Comment by VictorBjelkholm** [comment]
> How to get access to the infra

What kind of access you mean? Access to the actual instances? Also, I think we have separate access for the storage hosts and the rest of the instances.

> And it would not hurt to have a guide to create, deploy, play with a dev cluster

Yeah, I did this once, I'll do it again, and write down the process for it.

**Comment by hsanjuan** [comment]
SSH access I meant

**Comment by Kubuxu** [comment]
@hsanjuan You can create PR adding your file to here: https://github.com/ipfs/infrastructure/blob/master/base/env.sh#L9

**Comment by VictorBjelkholm** [comment]
@Kubuxu thanks!

Added it to a readme: https://github.com/ipfs/infrastructure/pull/205

**Pull request merged**
