### PR TITLE
Run go-ipfs dev0.4.0 on pluto and castor

### PR DESCRIPTION
**Pull request by lgierth**
Castor needs dev0.4.0 for NPM, and pluto will act as a rendezvous point for dev0.4.0 nodes.

ipfs/fs-repo-migrations#7 isn't merged yet, so both hosts don't have any of the pinnings. This includes the website, so I took pluto out of ipfs.io DNS.

### CODE REVIEW

**Comment by jbenet** [comment]
we should think through how to do the upgrade. 
- I think we'll need to keep running pre 0.4.0 bootstrappers for a while (1 or 2 months?).
- we should endeavor to make the https://ipfs.io gateway resolve stuff on both pre 0.4.0 and post 0.4.0.
- We will need to have a way of warning users that 0.4.0 is out (maybe 0.3.10 could warn about this)
- It would be very nice to have something like `wall` for the entire network to warn people about things. (discussed this a long time ago with @whyrusleeping) could be a feed of messages on ipfs itself, hosted at something like `http://<bootstrap-node>:80/refs/wall` (so private networks could use it too)

**Comment by cryptix** [comment]
:+1: for wall/message of the day

**Comment by lgierth** [comment]
> I think we'll need to keep running pre 0.4.0 bootstrappers for a while (1 or 2 months?).

agreed

> we should endeavor to make the https://ipfs.io gateway resolve stuff on both pre 0.4.0 and post 0.4.0.

Got a good idea how to do this cleanly, without trapping edge cases? We could have nginx fall back to another backend when the primary backend responds with a certain status (e.g. 404) -- but I'm not sure this would work well with legitimate 404s, i.e. we'd have both the 0.3 and 0.4 backends trying to resolve for some time, and make already slow responses twice as slow. Does this make sense?

> `http://<bootstrap-node>:80/refs/wall`

This already kinda works, cool, just need to add a `wall` link: http://venus.i.ipfs.io/refs/

**Comment by jbenet** [comment]
> Got a good idea how to do this cleanly, without trapping edge cases? We could have nginx fall back to another backend when the primary backend responds with a certain status (e.g. 404) -- but I'm not sure this would work well with legitimate 404s, i.e. we'd have both the 0.3 and 0.4 backends trying to resolve for some time, and make already slow responses twice as slow. Does this make sense?

yeah, makes sense. not sure either. :/

**Pull request merged**
